export const garosugilFloorGuideCards = [
  {
    id: "b1",
    eyebrow: "B1 FLOOR",
    title: "편하게 잠을 잘 수 있는 아늑한 침실",
    description: ["조용한 지하 1층에 자리한 독립적인 침실 공간입니다. 총 4개의 침실과 2개의 욕실이 마련되어 있어 여러 명이 함께 머물기에도 편안합니다. 최고급 침구와 은은한 조명으로 아늑한 휴식을 제공하며, 대형 스크린과 빔프로젝터, 명품 스피커로 특별한 시간을 즐길 수 있습니다."],
    imageSrc: "/images/section-images/가로수길점.jpg",
    imageAlt: "가로수길점 지하 침실",
    size: "large",
  },
  {
    id: "first",
    eyebrow: "1F FLOOR",
    title: "메인 거실 & 다이닝 주방",
    description: ["NORA STAY의 중심이 되는 메인 공간입니다. 대형 다이닝 테이블과 완벽히 구비된 최신식 주방이 구비된 거실이 있으며, 최고급 커피 머신 기기가 함께 배치되어 있습니다. 가족 모임이나 워크샵에 적합합니다."],
    imageSrc: "/images/section-images/가로수길점.jpg",
    imageAlt: "가로수길점 메인 다이닝 주방",
    size: "large",
  },
  {
    id: "second",
    eyebrow: "2F FLOOR",
    title: "야외 테라스 & 야외 힐링 공간",
    description: ["도심 속에서 자연을 만끽할 수 있는 2층 야외 테라스입니다. 푸른 인조잔디와 편안한 아웃도어 가구가 배치되어 있어, 따뜻한 햇살 아래 커피 한 잔의 여유를 즐기거나 밤하늘아래 고요함을 담아가는 테라스에서 하루를 정리하며,내일을 위한 여유를 충전하세요."],
    imageSrc: "/images/section-images/가로수길점.jpg",
    imageAlt: "가로수길점 야외 테라스",
    size: "large",
  },
  {
    id: "outdoor",
    eyebrow: "OUTDOOR SPACE",
    title: "도심 속 비밀 정원 & 테라스",
    description: ["가로수길 한복판에 숨겨진 넓은 야외 마당 정원과 입구 데크 테라스입니다. 웅장한 대저택 외관과 어우러져 단독 주택만이 줄 수 있는 프라이빗한 감성과 힐링을 완벽하게 선사합니다."],
    imageSrc: "/images/section-images/가로수길점.jpg",
    imageAlt: "가로수길점 비밀 정원과 테라스",
    size: "wide",
  },
  {
    id: "master",
    eyebrow: "MASTER SUITE",
    title: "럭셔리 마스터 침실 & 욕실",
    description: ["여유로운 휴식을 위해 준비된 마스터룸. 킹사이즈 또는 퀸사이즈 침대, 또는 슈퍼싱글 침대 2개가 준비되어 있으며, 2인용 테이블, 화장대, 수납공간을 갖춰 여행은 물론 장기 체류에도 편안한 시간을 제공합니다."],
    imageSrc: "/images/section-images/가로수길점.jpg",
    imageAlt: "가로수길점 마스터 침실",
    size: "wide",
  },
] as const;